library(tidyverse)
# csv<- list.files(
#   pattern = "\\.csv",
#   full.names = T) %>% 
#   lapply(read.csv) %>% 
#   bind_rows()
# 
# colnames(csv) = c("ID", "Price", "Date", "PostCode", "Type1", "Type2", "Type3", "House Num", "Flat", "Street Name", "Locality", "Town", "District", "County", "Type4", "Type5")
# fire=tail(csv)




#-----------------------------------------
#Cleaning Data For House Price

pop2020 = read_csv("C:/Users/aakri/Downloads/pp-2020.csv", show_col_types = FALSE)
pop2021 = read_csv("C:/Users/aakri/Downloads/pp-2021.csv", show_col_types = FALSE)
pop2022 = read_csv("C:/Users/aakri/Downloads/pp-2022.csv", show_col_types = FALSE)
pop2023 = read_csv("C:/Users/aakri/Downloads/pp-2023.csv", show_col_types = FALSE)

# Renaming the columns
colnames(pop2020) = c("ID" , "Price", "Year", "PostCode" , "PAON", "SAON", "FL", "House Num", "Flat", "Street Name",
                     "Locality", "Town" , "District", "County", "Type1", "Type2" )
colnames(pop2021) <-colnames(pop2020)
colnames(pop2022)<-colnames(pop2020)
colnames(pop2023)<-colnames(pop2020)
# 
# colnames(pop2021) = c("ID" , "Price", "Year", "PostCode" , "PAON", "SAON", "FL", "House Num", "Flat", "Street Name",
#                      "Locality", "Town" , "District", "County", "Type1", "Type2")
# colnames(pop2022) = c("ID" , "Price", "Year", "PostCode" , "PAON", "SAON", "FL", "House Num", "Flat", "Street Name",
#                      "Locality", "Town" , "District", "County" , "Type1", "Type2")
# colnames(pop2023) = c("ID" , "Price", "Year", "PostCode" , "PAON", "SAON", "FL", "House Num", "Flat", "Street Name",
#                      "Locality", "Town" , "District", "County" , "Type1", "Type2")

# Merging the datasets
HousePrices = pop2023 %>%
  add_row(pop2022)%>%
  add_row(pop2021) %>% 
  add_row(pop2020)


fire1=tail(HousePrices)
fire=head(HousePrices)

# Write the combined data to a new CSV file
write.csv(HousePrices, "merge-pop-data.csv")

data=read.csv("C:/Users/aakri/Downloads/clean data/clean data/merge-pop-data.csv")
view(data)





# Filtering Greater Manchester and Merseyside data
FilteredHousePrices = filter(data, County == 'GREATER MANCHESTER' | County == 'MERSEYSIDE')

FilteredHousePrices = FilteredHousePrices %>% 
  mutate(shortPostcode = str_trim(substring(PostCode, 1, 4))) %>%
  mutate(Year = str_trim(substring(Year, 1, 4))) %>% 
  select(PostCode, shortPostcode, Year, PAON, Price) %>% 
  na.omit()

# exporting filteredhouseprices data set to  csv
write.csv(FilteredHousePrices, "CleanedHousePrices.csv")


#Town
HousePricesclean <- read_csv("C:/Users/aakri/Downloads/clean data/clean data/CleanedHousePrices.csv", show_col_types = FALSE)

population = read_csv("C:/Users/aakri/Downloads/Population2011_1656567141570.csv", show_col_types = FALSE)
# Clean the population data
population_data <- population %>%
  mutate(shortPostcode = str_trim(substring(Postcode, 1, 4))) %>% 
  group_by(shortPostcode) %>% 
  summarise(Population = sum(as.numeric(gsub(",", "", Population))))



FilteredTown = filter(data, County == 'GREATER MANCHESTER' | County == 'MERSEYSIDE')

# Join the house prices data with population data
FilteredTown1 = FilteredTown %>% 
  mutate(shortPostcode = str_trim(substring(PostCode, 1,4))) %>%
  mutate(Year = str_trim(substring(Year, 1,4))) %>% 
  left_join(population_data,by="shortPostcode") %>% 
  select(PostCode, shortPostcode, Year, Town, District, County) %>% 
  group_by(shortPostcode) %>%
  filter(row_number()==1) %>%
  arrange(County) %>% 
  na.omit()
write.csv(FilteredTown1, "CleanedData_Towns.csv")



#Ten houses with the highest prices
Filtered_high_houseprice <- data %>%
  select(County, House.Num, Price,Street.Name,Year) %>%
  arrange(desc(Price)) %>%
  head(10)
print(Filtered_high_houseprice)
# exporting filteredhouseprices data set to  csv
write.csv(Filtered_high_houseprice, "/C:/Users/aakri/Downloads/clean data/CleanData/Cleaned_Top_HousePrices.csv")
# Read Towns data
Towns <- read_csv("C:/Users/aakri/Downloads/clean data/clean data/CleanedData_Towns.csv") %>%
  select(shortPostcode, Town, District, County)

# Read HousePrices data
HousePrices <- read_csv("C:/Users/aakri/Downloads/clean data/clean data/CleanedHousePrices.csv", show_col_types = FALSE)


HousePricesclean <- HousePrices %>% 
  left_join(Towns, by ="shortPostcode")  %>% 
  na.omit()
  
  # Filter for the year 2023
HousePrices_2023 <- filter(HousePricesclean, Year == 2023)

# Calculate average prices by district and county
AveragePrices_2023 <- HousePrices_2023 %>%
  group_by(District, County) %>%
  summarise(AveragePrice = mean(Price, na.rm = TRUE))

# Create a bar chart
ggplot(AveragePrices_2023, aes(x = District, y = AveragePrice, fill = County)) +
  geom_bar(stat = "identity") +
  labs(title = "Average House Prices by District (2023)",
       x = "District", y = "Average Price") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels = scales::comma_format())
  
  
  # BOXPLOT Average house prices by district (2019-2021)
HousePricesclean %>% 
  group_by(District) %>% 
  ggplot(aes(x = District, y = Price, fill=District)) +
  scale_y_continuous(limits=c(0,2000000), breaks = seq(0,2000000,200000), 
                     label = euro) +
  geom_boxplot() +
  coord_flip() +
  labs(title="2020-2023 house prices by district")


# Calculate average prices by year
AveragePrices_byYear <- HousePricesclean %>%
  group_by(Year) %>%
  summarise(AveragePrice = mean(Price, na.rm = TRUE))

# Create a line graph with points and formatted labels
ggplot(AveragePrices_byYear, aes(x = Year, y = AveragePrice)) +
  geom_line(size = 1.5, color = "lightgrey") +
  geom_point(size = 3, color = "steelblue") +
  geom_text(aes(label = scales::dollar(AveragePrice, prefix = "€")), vjust = -0.85, hjust = 0.5, size = 3, color = "black") +
  scale_y_continuous(labels = scales::dollar_format(prefix = "€"), breaks = seq(0, 300000, 5000)) +
  labs(title = "Average House Prices Over Time (2019-2023)",
       x = "Year", y = "Average Price") +
  theme_minimal()
 

# Ensure Year is converted to a numeric or date format if it's not already
HousePricesclean <- mutate(HousePricesclean, Year = as.numeric(Year))

# Create a time series plot
ggplot(HousePricesclean, aes(x = Year, y = Price, group = 1)) +
  geom_line() +
  labs(title = "House Prices Over Time",
       x = "Year", y = "Price") +
  theme_minimal()
  
  
  library(ggplot2)

# Assuming HousePricesclean is already read and contains the necessary data

ggplot(data = HousePricesclean) +
  geom_point(mapping = aes(x = Price, y = County)) +
  labs(title = "Scatter Plot of House Prices by County",
       x = "Price", y = "County", size = "District") +
  theme_minimal()


